# Generated by Django 4.2.4 on 2023-10-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feastfiles', '0002_alter_weeat_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=30)),
                ('username', models.CharField(max_length=100)),
                ('password', models.IntegerField()),
            ],
        ),
    ]
